package_name: ???

python_version: "3.12"

name: init

run:
  code_privacy_confirmation: true
  remote_url_prompt: true


python_submodules:
  - data
  - models
  - utils

uv:
  timeout: 100000
  packages:
    - dvc
    - ruff
    - pre-commit
    - wandb
    - torch
    - numpy
    - scikit-learn
    - ipython
    - jupyter
    - tqdm
    - matplotlib
    - seaborn
    - hydra-core
    - omegaconf
    - loguru
    - pandas
    - torcheval
    - pytest
    - pytest-cov

mhpy_url: mhpy[ml] @ git+https://github.com/NikitaGordia/mhpy.git


data_states:
  - raw
  - interim
  - processed

hydra:
  submodule: config
  configs:
    - model
    - train
    - data
    - env
    - exp

other_dirs:
  - notebooks
  - scripts

debug: false

